### ISSUE TITLE
jq-300 firmware dump fails to load

### ISSUE THREAD

**Issue by brainstorm** [hank/ghidra-esp8266#3]
While trying to analyze the firmware dumped in https://github.com/xoseperez/espurna/issues/1644, it seems like the loader cannot take this particular (dumped) binary... would you be interested in this sample to make your loader more robust?:

```
----- Loading /Users/romanvg/dev/jq300-fw/jq-300.bin -----
not an ESP8266 file.
java.io.IOException: not an ESP8266 file.
	at ghidraesp8266_2.ESP8266Header.<init>(ESP8266Header.java:25)
	at ghidraesp8266_2.ESP8266Module.<init>(ESP8266Module.java:23)
	at ghidraesp8266_2.GhidraESP8266_2Loader.load(GhidraESP8266_2Loader.java:166)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Essentially the `ESP_MAGIC_BASE` is not found in that firmware, but I can ascertain that it is indeed a valid ESP8266 image.

**Comment by hank** [comment]
Thanks! I did this plugin as a little project on the plane to DEFCON and I'm not actively working on it. If you'd like to submit a pull request with a change to make it more robust, that'd be great!

**Comment by Juan-ma** [comment]
I found the same problem as @brainstorm.  In my case the first byte of the image match the magic 0xe9 byte, but then the ESP8266 loader fails parsing the ROM header in 0x1000 address. The problem here is that GhidraESP8266_2 works only with an old ROM format whose header has the magic 0xe9, but it seems that our image has a new format as described [here](https://richard.burtons.org/2015/05/17/decompiling-the-esp8266-boot-loader-v1-3b3/). This new ROM format has a different header with a new magic 0xea40.

Now I have made a few changes to the GhidraESP8266_2 code to adapt it to this new format. Now it parses the new header fine although then it gives a few warnings parsing some sectors. Maybe other people can help us to carry this out.

My problem is that I would like to share the code, but I don't know how to do it.

**Comment by hank** [comment]
If you fork the repo, then commit your changes to a branch in your copy, you can make a pull request.

**Comment by Juan-ma** [comment]
I don't know if I have understood it at all, but I have done a fork with the modification [here](https://github.com/Juan-ma/ghidra-esp8266.git).

**Comment by brainstorm** [comment]
@Juan-ma I just tested your changes locally with Ghidra compiled from master but I'm getting the following error while following the installation instructions [you detailed in the README.md (thanks!)](https://github.com/Juan-ma/ghidra-esp8266/commit/31889425e5f05db77d470888aa5f785bb15e69bb):

```
Language not found for 'Xtensa:LE:32:default'
ghidra.program.model.lang.LanguageNotFoundException: Language not found for 'Xtensa:LE:32:default'
	at ghidra.program.util.DefaultLanguageService.getLanguage(DefaultLanguageService.java:109)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:333)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Would you mind testing/taking another look at it (with upstream Ghidra from `master`)? The Language Spec for Xtensa doesn't seem to be listed when I import a new binary :/

**Comment by Juan-ma** [comment]
Sorry, maybe you have to install this [ghidra-xtensa](https://github.com/yath/ghidra-xtensa) extension before. Please, tell me if you solve the problem, so I will update the install instructions.

**Comment by brainstorm** [comment]
Ah, my bad, it has been a while since I touched those extensions ;)

It does seem to load something now, but I'm not sure it's getting all the sections of the binary image? I'm seeing too few strings, only related to the bootloader, AFAICT:

<img width="658" alt="Screen Shot 2021-09-27 at 10 31 21 pm" src="https://user-images.githubusercontent.com/175587/134908409-ac2cee85-f50b-4979-91a1-c11cf19bfbba.png">

I suspect that we should see more strings from the user code, no? I've been looking into converting the `.bin` image to `.elf` independently from this extension, as proposed in https://github.com/espressif/esptool/issues/604... I suspect that with this extension only the very first section is being loaded and therefore we are not seeing the rest? See:

https://github.com/espressif/esptool/wiki/Firmware-Image-Format
https://microcontrollerelectronics.com/decoding-an-esp8266-firmware-image/
https://boredpentester.com/reversing-esp8266-firmware-part-3/
https://github.com/dentraitim/esp-bin2elf

Running the script(s) from the latter repo I get little amount of code (just 3,2KB and barely 7 functions according to radare2) in its sections as well, though:

```
% ./user_bin_to_elf.py jq-300.bin
Image version: 1
Entry point: 0x40100294
3 segments
Segment 1: len 0x00574 load 0x40100000 file_offs 0x00000008 [IRAM]
Segment 2: len 0x00308 load 0x3ffe8000 file_offs 0x00000584 [DRAM]
Segment 3: len 0x0021c load 0x3ffe8308 file_offs 0x00000894 [DRAM]
Wrote: jq-300.bin.elf
Checksum: c0 (valid)

% ls -alh jq-300.bin
-rw-r--r-- 1 rvalls staff 4.0M Sep 26 22:03 jq-300.bin

% ls -alh jq-300.bin.elf
-rw-r--r-- 1 rvalls staff 3.2K Sep 27 22:42 jq-300.bin.elf

 % r2 jq-300.bin.elf
[0x40100294]> aaaa
[Warning: set your favourite calling convention in `e anal.cc=?`
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Finding and parsing C++ vtables (avrr)
[x] Finding xrefs in noncode section (e anal.in=io.maps.x)
[x] Analyze value pointers (aav)
[x] Value from 0x40100000 to 0x40100574 (aav)
[x] 0x40100000-0x40100574 in 0x40100000-0x40100574 (aav)
[x] Emulate functions to find computed references (aaef)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information (aanr)
[x] Finding function preludes
[x] Enable constraint types analysis for variables
[0x40100294]> afl
0x40100294   71 733          entry0
0x4010000c    7 64           fcn.4010000c
0x401000ac    4 181          fcn.401000ac
0x40100170    2 84           fcn.40100170
0x40100054    6 66           fcn.40100054
0x401001cc    4 54           fcn.401001cc
0x40100204    1 23           fcn.40100204
[0x40100294]>
```

This `esp-bin2elf` repo needs a couple of minor tweaks to be functional in 2021 though:

```diff
(reveng) rvalls@m1 esp-bin2elf % git diff
diff --git a/esp_elf.py b/esp_elf.py
index d6ab599..76a7867 100644
--- a/esp_elf.py
+++ b/esp_elf.py
@@ -1,3 +1,5 @@
+#!/usr/bin/env python3
+
 # esp-bin2elf written by Joel Sandin <jsandin@gmail.com>
 #
 # MIT licence
diff --git a/requirements.txt b/requirements.txt
index a22d4b9..4157a59 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1 +1,2 @@
-elffile
+coding
+https://github.com/slorquet/elffile2/archive/refs/tags/v0.7.tar.gz
```

Please continue driving this, @Juan-ma, good job! ;)

**Comment by Juan-ma** [comment]
I know my fork is not locating the segments correctly, I'm working on it but I don't have many time :-(

I suspect the problem with user_bin_to_elf.py and esptool, etc. is that all they only analyze the first header and the n (usually 3) segments after it that I think it is the bootloader code, but we need the user code that is pointed in the second header located at 0x1000 in the binary image.

I'm not sure at all, but I think our binary image has this structure:

- **First Header at 0x0000**: e9 03 00 00 xx xx 10 40 -> It indicates 3 segments (that I think they are bootloader code)
- We don't care the first 3 segments because they seems to be bootloader code.
- **Seccond header at 0x1000**: ea 04 00 01 04 00 10 40  00 00 00 00 xx yy zz 00 -> Indicates entry point at 0x40100004 (ESP8266 address) and the next 0x000zzyyxx bytes in the image I think may be some ESP8266 API lib code.
- We don't care the next 0x000zzyyxx bytes because they seem to be some ESP8266 API lib code.
- At 0x1000 + 0x10 + 0x000zzyyxx = 0x000abcde we have a **new header with the original format**, that is 0xe9 magic: e9 03 00 40 04 00 10 40  00 00 10 40 xx yy 00 00. Now we have **new 3 user segments**, a **new entry point 0x40100004** and the address and length of the first user segment: 0x0000yyxx bytes at 0x40100000 (ESP8266 IRAM address).
- The second user segment at 0x000abcde + 0x10 + 0x0000yyxx = 0x000ghijk: 00 80 fe 3f xx yy 00 00 that is 0x0000yyxx bytes at 0x3ffe8000 (ESP8266 DRAM address). 
- The third user segment at 0x000ghijk + 0x08 + 0x0000yyxx = 0x000lmnop: 60 8a fe 3f xx yy 00 00 that is 0x00yyxx bytes at 0x3ffe8a60 (ESP8266 IRAM address).

I have never used radare2 but I think the hint would be modifying user_bin_to_elf.py to extract the elf file related to the 3 user segments and then pass it through radare2.

**Comment by brainstorm** [comment]
My time is limited as well, but I see you have a good understanding of the .bin makeup, this is promising!

> We don't care the next 0x000zzyyxx bytes because they seem to be some ESP8266 API lib code.

We actually should care about that section since it can be a bit difficult to analyze the firmware without those symbols. Once that section is included in Ghidra we can load signatures (.fidb?) and have much nicer function names and xrefs.

> I have never used radare2 but I think the hint would be modifying user_bin_to_elf.py to extract the elf file related to the 3 user segments and then pass it through radare2.

Yes, that was the idea I was working on it for just a few minutes. And that'd be not only the 3 segments, which are just 3.2KB of payload, but all we need for a good analysis as I mentioned above comment with the SDK lib(s).

But please do continue with your efforts, they definitely look more promising than my short poking-at-this session ;)

**Comment by Juan-ma** [comment]
I have managed to extract the user elf with a litle trick. While we have  at 0x1000 the V2 header like

ea 04 00 01 04 00 10 40 00 00 00 00 b0 98 04 00

we can get the number of bytes to skip, ie. 0x000498b0 to look at the seccond user header using hexdump. Now we can cut the image whith tail to get the seccond user header and segments skipping the first (0x1000 + 0x10 + 0x000498b0) bytes. While _tail -c_ only accept decimal arguments, we do:

`hexdump flashROM.bin -s 0x100c -n 4 -e'"%u\n"'`

In this case it outputs 301232. To get the number of bytes to skip we add to this 0x1000 + 0x10 = 4096 + 16 = 4112. So we have to skip 301232 + 4112 = 305345 bytes. Now we use tail to cut the image:

`tail -c +305345 flashROM.bin > flashROM.user.bin`

And now we can use esp-bin2elf.py:

```
$ esp-bin2elf-master/user_bin_to_elf.py flashROM.user.bin 
Image version: 1
Entry point: 0x40100004
3 segments
Segment 1: len 0x07fac load 0x40100000 file_offs 0x00000008 [IRAM]
Segment 2: len 0x00a60 load 0x3ffe8000 file_offs 0x00007fbc [DRAM]
Segment 3: len 0x03e08 load 0x3ffe8a60 file_offs 0x00008a24 [DRAM]
Wrote: flashROM.user.bin.elf
Checksum: 6d (valid)
```

Then you can load it with r2 and it finds a lot of functions. The problem is that we don't have the API segment loaded and maybe it would be necesary as you mentioned... I have never use r2, but I'm going to have a look.
esp-bin2elf uses esptool but while it is supposed to manage V2 bootloader images, I think it doesn't fine.
